<a href="https://colab.research.google.com/github/zvyag/PyTorch-for-Deep-Learning-and-Computer-Vision-Course-All-Codes-/blob/master/pytorch_hello.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip3 install torch

In [0]:
import torch
import numpy as np

#### create 1D tensor

In [2]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [3]:
f = torch.FloatTensor([1, 2, 3, 4])
print(f)

tensor([1., 2., 3., 4.])


#### check the datatype

In [4]:
# check the data type
print(v.dtype)
print(f.dtype)

torch.int64
torch.float32


**check the size**

In [5]:
print(v.size())
print(f.size())

torch.Size([6])
torch.Size([4])


**rearrange the elements**

In [6]:
v.view(6, 1)  # similar to reshape in numpy

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [7]:
v.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
v.view(3, -1)  # second dimension is infered from the original shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
v

tensor([1, 2, 3, 4, 5, 6])

#### element access

In [10]:
v[0]

tensor(1)

In [11]:
v[1:4]  # stop index is exclusive!

tensor([2, 3, 4])

In [12]:
v[1:]

tensor([2, 3, 4, 5, 6])

**convert np arrays to tensors and vice versa**

In [13]:
a = np.array([1, 2, 3, 4, 5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [14]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]


**matrix multiplication**

In [16]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [17]:
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [18]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [19]:
mat_a@mat_b

tensor([[ 29, -16],
        [ 38,   6]])