<a href="https://colab.research.google.com/github/zvyag/PyTorch-for-Deep-Learning-and-Computer-Vision-Course-All-Codes-/blob/master/pytorch_hello.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch
import numpy as np
import torch.nn as nn
#from torch.nn import Linear

#### create 1D tensor

In [0]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [0]:
f = torch.FloatTensor([1, 2, 3, 4])
print(f)

tensor([1., 2., 3., 4.])


#### check the datatype

In [0]:
# check the data type
print(v.dtype)
print(f.dtype)

torch.int64
torch.float32


**check the size**

In [0]:
print(v.size())
print(f.size())

torch.Size([6])
torch.Size([4])


**rearrange the elements**

In [0]:
v.view(6, 1)  # similar to reshape in numpy

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [0]:
v.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [0]:
v.view(3, -1)  # second dimension is infered from the original shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [0]:
v

tensor([1, 2, 3, 4, 5, 6])

#### element access

In [0]:
v[0]

tensor(1)

In [0]:
v[1:4]  # stop index is exclusive!

tensor([2, 3, 4])

In [0]:
v[1:]

tensor([2, 3, 4, 5, 6])

**convert np arrays to tensors and vice versa**

In [0]:
a = np.array([1, 2, 3, 4, 5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [0]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]


**matrix multiplication**

In [0]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [0]:
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [0]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [0]:
mat_a@mat_b

tensor([[ 29, -16],
        [ 38,   6]])

**derivatives**

In [0]:
x = torch.tensor(2.0, requires_grad=True)
y = 9*x**4 + 2*x**3 + 3*x**2 + 6*x + 1
y.backward()
x.grad

tensor(330.)

In [0]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)
y = x**2 + z**3
y.backward()
print(x.grad)
print(z.grad)

tensor(2.)
tensor(12.)


**linear model**

In [0]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [0]:
def forward(x):
  return w*x + b

In [7]:
x = torch.tensor([4, 7])
forward(x)

tensor([13, 22], grad_fn=<AddBackward0>)

**with linear class**

In [0]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)

In [12]:
print(model.bias)
print(model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True)
Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [14]:
x = torch.tensor([[2.0], [3.0]])
print(model(x))

tensor([[0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


**custom models**

In [0]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
    
  def forward(self, x):
    return self.linear(x)

In [8]:
torch.manual_seed(1)
model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
